config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
    get '/signin', to:  'devise/sessions#create' , as: :signin
    get 'signup' , to:  'devise/registrations#new', as: :signup
  end
    
  get 'events/delete' => 'events#destroy'
  get 'rsvp_events/delete' => 'rsvp_events#destroy'
  get 'delete_review' => 'reviews#destroy'
  
  resources :events do  
    collection do 
      get 'past_events' => 'events#past'
      get 'active_events' => 'events#active'
      get 'todays' => 'events#today'
      get 'all_events' => 'events#all'
      get 'top_events' => 'events#top'
      get 'highest_rated' => 'events#highest_rated'
    end
  end
     
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :events

  resources :events do
    resources :reviews
  end
    

  resources :events do
     post '/rsvp_events/create', to: 'rsvp_events#create', on: :member
  end
    
  root :to => 'home#index'
  # get 'sessions/new'
  # get 'sessions/destroy'
  # post 'sessions/create'
  #get '/auth/:provider/callback' => "sessions#create"
    
  #post '/rsvp_events/create', to: 'rsvp_events#create'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :planner, class_name: 'User', foreign_key: 'planner_id'
  belongs_to :category
  validates_presence_of :name, :location, :description, :start_date, :end_date
  has_many :rsvp_events, foreign_key: :attending_event_id
  has_many :participants, through: :rsvp_events, dependent: :destroy
  has_many :reviews, foreign_key: :reviewing_event_id
  has_many :reviewers, through: :reviews, dependent: :destroy
  validates_associated :category, message: 'is already on list or invalid format.'
  alias_attribute :start_time, :start_date
  alias_attribute :end_time, :end_date

  validate :date_must_be_current, if: :has_date_range?
  validate :correct_date_range, if: :has_date_range?
  validate :no_overlapping_events, on: :create

  # before_save :upcase_name

  scope :overlapping, lambda { |start_date, end_date|
    where(
      'start_date <= :end_date AND :start_date <= end_date',
      start_date: start_date, end_date: end_date
    )
  }

  def self.top
    select('events.*, COUNT(rsvp_events.id) AS rsvp_events_count')
      .joins(:rsvp_events)
      .group('events.id')
      .order('rsvp_events_count DESC')
      .limit(5)
  end

  # def self.highest_rated
  #   joins(:reviews).select("*, avg(reviews.rating) as average_rating").group("events.id").order("average_rating DESC").limit(3)
  # end

  def self.highest_rated
    select('events.*, avg(reviews.rating) AS average_rating').joins(:reviews).group('events.id').order('average_rating DESC').limit(5)
  end

  def no_overlapping_events
    event = Event.overlapping(start_date, end_date)
    overlaps = event.where('planner_id = ?', planner_id)

    if overlaps.any?
      dates = overlaps.map do |e|
        [e.start_date.strftime('Start Of Event : %A, %b %e, at %l:%M %p'), e.end_date.strftime('End Of Event : %A, %b %e, at %l:%M %p')].join(' to ')
      end.join(', ')
      errors.add(:base, "must not overlap existing events. Overlaps: #{dates}")
    end
  end

  def self.active_event
    where('end_date > ?', DateTime.now)
  end

  def self.past_event
    where('end_date < ?', DateTime.now)
  end

  def self.todays_event
    where('start_date = ?', Date.today)
  end

  def has_date_range?
    start_date.present? && end_date.present?
  end

  def date_must_be_current
    unless start_date >= DateTime.now
      errors.add(:start_date, 'must be on or after current date')
    end
  end

  def correct_date_range
    unless end_date >= start_date
      errors.add(:end_date, 'must be on or after start of event')
    end
  end

  def upcase_name
    name.upcase!
  end
  
  def presence
    self if present?
  end

  


  def category_attributes=(category_attributes)
    build_category(category_attributes) unless category_attributes[:name].blank?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_time_zone, if: :user_signed_in?

  def index
    @user = current_user

    if params[:search]
      params[:search].downcase!
      @events = Event.where('name LIKE ?', "%#{params[:search]}%")
    elsif params[:category]
      @category = Category.find_by(id: params[:category][:id])
      @events = @category.events
    else
      @events = Event.active_event
    end
  end

  def show
    # raise params.inspect
    @user = current_user
    @event = Event.find(params[:id])
    @rsvp_event = RsvpEvent.find_by(participant_id: @user.id, attending_event_id: @event.id)
    @review = Review.find_by(reviewer_id: @user.id, reviewing_event_id: @event.id)
    @rsvp_events = RsvpEvent.where(attending_event_id: @event.id)
    @reviews = Review.where(reviewing_event_id: @event.id)
  end

  def new
    # @user = current_user
    @event = Event.new
    @event.build_category
  end

  def create
    # raise params.inspect
    @user = current_user
    @event = @user.events.build(event_params(:name, :location, :description, :search, :planner_id, :start_date, :end_date, :category_id, category_attributes: [:name]))

    if @event.save
      flash[:message] = "YOU HAVE CREATED #{@event.name.upcase}"
      redirect_to event_path(@event)
    else
      @event.build_category
      render :new
    end
  end

  def edit
    # raise params.inspect
    # @user = current_user
    @event = Event.find(params[:id])
    @event.build_category
  end

  def update
    @user = current_user
    @event = Event.find(params[:id])
    if @event.update(event_params(:name, :date, :location, :description, :planner_id, :start_date, :end_date, :category_id, category_attributes: [:name]))
      flash[:message] = "YOU HAVE UPDATED #{@event.name.upcase}"
      redirect_to event_path(@event)
    else
      @event.build_category
      render :edit
    end
  end

  def destroy
    # raise params.inspect
    @user = current_user
    @event = Event.find(params[:id])
    @event.destroy
    flash[:message] = "YOU HAVE DELETED #{@event.name.upcase}"
    redirect_to events_path(@user)
  end

  def past
    @events = Event.past_event
    render :past
  end

  def active
    @events = Event.active_event
    render :index
  end

  def today
    @events = Event.todays_event
    render :index
  end

  def all
    @events = Event.all
    render :all
  end

  def top
    @events = Event.top
    render :top_rated
   end

  def highest_rated
    @events = Event.highest_rated
    render :event_ratings
  end

  private

  def event_params(*args)
    params.require(:event).permit(*args)
  end

  def set_time_zone
    Time.zone = 'Eastern Time (US & Canada)'
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def start_of_event(event)
    event.start_date.strftime('START OF EVENT : %A, %b %e, at %l:%M %p')
  end

  def end_of_event(event)
    event.end_date.strftime('END OF EVENT : %A, %b %e, at %l:%M %p')
  end
end

app/views/events/_events_cards.html.erb
<div class="row">

  <% @events.each do |event| %>

  <div class="col-sm" style="padding-bottom: 10px;">
    <div class="card" style="width: 18rem;">
      <div class="card-body">

        <h5 class="card-title">
          <%=event.name.upcase %>
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <%= start_of_event event %>
        </h6>
        <h6 class="card-subtitle mb-2 text-muted">
          <%= end_of_event  event %>
        </h6>
        <h6 class="card-subtitle mb-2 text-muted">LOCATION:
          <%= event.location.upcase %>
        </h6>
        <p class="card-text">
          <%= event.description.truncate(25, separator: /\s/) %>
        </p>
        <a href="<%= event_path(event) %>" class="card-link">Event Details</a>

      </div>
    </div>
  </div>

  <br />
  <br />

  <% end %>

   

app/views/events/_form.html.erb
<% if @event.errors.any? %>
    <h4 style="color:#FF5500"><%= @event.errors.full_messages.to_sentence %></h4>
<% end %>

<%= form_for [@event] do |f|%>
    <%= f.hidden_field :planner_id %>

    <div class="form-group">
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "Pick a Category"%>
        <%= f.fields_for :category do |builder| %>
        <p>-or-</p><%= builder.text_field :name, value: nil, placeholder:"New Gategory"%><br><br>
        <% end %>
    </div>
        
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :start_date %>
        <%= f.datetime_select :start_date, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :end_date %>
        <%= f.datetime_select :end_date, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :location %>
        <%= f.text_field :location, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area  :description,  class: 'form-control'%>
    </div>

    <%= f.submit %>
<% end %>

app/views/events/_top_link.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-3">
      <p> <%= link_to "HIGHEST RATED EVENT", highest_rated_events_path %></p>
    </div>
    <div class="col-lg-3">
      <p><%= link_to "PAST EVENTS", past_events_events_path %></p>
    </div>
    <div class="col-lg-3">
      <p><%= link_to "ALL EVENTS", all_events_events_path %></p>
    </div>
    <div class="col-lg-3">
      <p><%= link_to "TOP EVENTS", top_events_events_path %></p>
    </div>
  </div>

  <div class="links">

    <br><br>

app/views/events/all.html.erb
  <%= render 'top_link' %>

  <br><br>


  <h2 align="center" style="padding-top: 10Ppx; color:black;  padding-bottom: 10px;">LIST OF ALL EVENTS</h2>
  <br />
 
  <%= render 'events_cards' %>
  
  <br />
  <br />

   </div>
   </div>

  <br/>
  <br/>
  <br/>

app/views/events/edit.html.erb
<div class="container">
  <h5 class="display-4" align="center" style="padding-top: 10Ppx; color:black;  padding-bottom: 10px;">EDIT EVENT</h5>

  <%= render partial:'form', locals: {user: @user, event: @event} %>

</div>

app/views/events/event_ratings.html.erb
<body id="event_index">
  <%= render 'top_link' %>

      <br><br>


      <h2  align="center" style="padding-top: 10Ppx; color:black;  padding-bottom: 10px;">LIST OF HIGHEST RATED EVENTS</h2>
        <br />

        <% unless @events.blank? %>
        <h5 align="center"
          style="padding-top: 10Ppx; color:black;  padding-bottom: 10px;">THE HIGHEST RATED EVENT IS <%=@events.first.name.upcase %></h5>
        <% end %>

        <br/>
         <%= render 'events_cards' %>
      
    </div>
  </div>
</body>

app/views/events/index.html.erb
  <%= render 'top_link' %>

      <br><br>


      <h2  align="center" style="padding-top: 10Ppx; color:black;  padding-bottom: 10px;"> ALL UPCOMING EVENTS</h2>
        <br />
        
      
      <div class="filter">
        <%= form_tag '#', :method => :get do%>
        <%= collection_select :category, :id, Category.all, :id, :name, placeholder: "FILTER BY CATEGORY" %>
        <%= submit_tag 'Filter' %>
        <% end %>
      </div>
     
      <%= form_tag events_path, :method => :get do %>
        <%= text_field_tag :search %>
        <%= submit_tag 'Search'%>
      <% end %>

    </div>
    <br />
    <%= render 'events_cards' %>

      <br/>
      <br />
      <div class="w-100"></div>
        <div id="events">
          <%= month_calendar events: @events do |date, events| %>
            <%= date %>
            <% events.each do |event| %>
              <%= event.name %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <br />
  <br />

  <br />

app/views/events/new.html.erb
<div class="container">
  <h4 class="display-4" align="center" style="padding-top: 10Ppx; color:black;  padding-bottom: 10px;">CREATE A NEW EVENT</h4>

    <%= render partial:'form', locals: {user: @user, event: @event} %>

</div>

app/views/events/past.html.erb
<body id="event_index">
  <%= render 'top_link' %>

  <br><br>


  <h2 align="center" style="padding-top: 10Ppx; color:black;  padding-bottom: 10px;">LIST OF PAST EVENTS</h2>
  <br />
  <br/>

  
  <%= render 'events_cards' %>
  
</body>

app/views/events/show.html.erb
<div class="container">
  <h2 style=" padding-top: 12px; color:#483D8B; padding-bottom: 12px;">

    <%= @event.name.upcase %>
  </h2>
  <br />
  <h4 style="color:#000080">EVENT PLANNER:
    <%= @event.planner.full_name.upcase %>
  </h4>
  <br />
  <h4 style="color:#000080">CATEGORY:
    <%= @event.category.name %>
  </h4>
  <h5>No. OF PARTICIPANTS : <%= @event.participants.count %></h5>
  <h4>
    <%= start_of_event(@event) %>
  </h4>
  <h4>
    <%= end_of_event(@event) %>
  </h4>
  <h4>LOCATION:
    <%= @event.location.upcase %>
  </h4>
  <br />

  <h5 style="color: #000033">DESCRIPTION:
    <%= @event.description.upcase %>
  </h5>

  <h5>EVENT PARTICIPANTS:</h5>
  <% @rsvp_events.each do |rsvp| %>
  <h6 style="color:#2F4F4F">


    <ul>
      <li> NAME:
        <%= rsvp.participant.full_name.upcase %>
        &ensp; EMAIL:
        <%= rsvp.participant.email.upcase %>
      </li>

    </ul>
  </h6>
  <% end %>

  <h5><%=@event.name.upcase %> REVIEWS:</h5>
  <% @reviews.each do |review| %>
  <h6 style="color:#2F4F4F">


    <ul>
      <li>
        REVIEWER :
        <%= review.reviewer.full_name.upcase %>&ensp;

        RATING :
        <%= review.rating %>&ensp;

        REVIEW :
        <%= review.body.upcase %>
      </li>

    </ul>
  </h6>
  <% end %>

  <br />
  <a class="btn btn-outline-primary btn-lg btn-block" href="<%=events_url %>">ALL UPCOMING EVENTS</a>
  <br />
  <a class="btn btn-outline-info btn-lg btn-block" href="<%= event_reviews_path(@event) %>">SEE ALL
    REVIEWS</a>
  <br />

  <% if @event.planner_id != current_user.id  %>
  <div class="rsvp">
    <%= button_to "RSVP NOW", rsvp_events_create_event_path(event_id: @event.id), class: "btn btn-outline-success btn-lg btn-block" %>
    <br>

    <% unless @rsvp_event.blank? %>
    <% if @rsvp_event.participant_id = current_user.id %>
    <a class="btn btn-outline-warning btn-lg btn-block" href="<%= rsvp_events_delete_path(id: @event.id) %>">CANCEL
      RSVP</a>
    <br />
    <a class="btn btn-outline-info btn-lg btn-block" href="<%= new_event_review_path(@event) %>">REVIEW
      EVENT</a>

    <br />
    <% unless @review.blank? %>
    <% if @review.reviewer_id = current_user.id %>

    <a class="btn btn-outline-info btn-lg btn-block" href="<%= edit_event_review_path(@event) %>">EDIT REVIEW</a>
    <br />


    <a class="btn btn-outline-warning btn-lg btn-block" href="<%= delete_review_path(id: @event.id) %>">DELETE
      REVIEW</a>
    <br />
    <br />

    <br />
  </div>
  <% end %>
  <% end %>
  <% end %>
  <% end %>
  <% end %>



  <% if @event.planner_id == @user.id %>
  <a class="btn btn-outline-info btn-lg btn-block" href="<%= edit_event_path(@event) %>">EDIT EVENT</a>
  <br />
  <a class="btn btn-outline-success btn-lg btn-block" href="/users/<%= @user.id %>">YOUR EVENTS</a>
  <br />
  <a class="btn btn-outline-warning btn-lg btn-block" href="<%= events_delete_path(id: @event.id) %>">DELETE EVENT</a>


</div>

<br />
<% end %>
<br />

<br />

<br />

app/views/events/top_rated.html.erb
<body id="event_index">
  <%= render 'top_link' %>

  <br><br>


  <h2 align="center" style="padding-top: 10Ppx; color:black;  padding-bottom: 10px;">LIST OF TOP EVENTS</h2>
  <br />

  <% unless @events.blank? %>
  <h5 align="center" style="padding-top: 10Ppx; color:black;  padding-bottom: 10px;">THE EVENT WITH THE MOST RSVP IS
    <%=@events.first.name.upcase %></h5>
  <% end %>

  <br />
  <%= render 'events_cards' %>

  </div>
  </div>
</body>