config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
    get '/signin', to:  'devise/sessions#create' , as: :signin
    get 'signup' , to:  'devise/registrations#new', as: :signup
  end
    
  get 'events/delete' => 'events#destroy'
  get 'rsvp_events/delete' => 'rsvp_events#destroy'
  get 'delete_review' => 'reviews#destroy'
  
  resources :events do  
    collection do 
      get 'past_events' => 'events#past'
      get 'active_events' => 'events#active'
      get 'todays' => 'events#today'
      get 'all_events' => 'events#all'
      get 'top_events' => 'events#top'
      get 'highest_rated' => 'events#highest_rated'
    end
  end
     
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :events

  resources :events do
    resources :reviews
  end
    

  resources :events do
     post '/rsvp_events/create', to: 'rsvp_events#create', on: :member
  end
    
  root :to => 'home#index'
  # get 'sessions/new'
  # get 'sessions/destroy'
  # post 'sessions/create'
  #get '/auth/:provider/callback' => "sessions#create"
    
  #post '/rsvp_events/create', to: 'rsvp_events#create'
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cerulean/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-C++cugH8+Uf86JbNOnQoBweHHAe/wVKN/mb0lTybu/NZ9sEYbd+BbbYtNpWYAsNP" crossorigin="anonymous">
    <title>RailsEventApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a class="navbar-brand" href="/">RAILS EVENT APP</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navBarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <% if user_signed_in? %>

          <li class="nav-item active">
            <% @user = current_user %>
            <a class="nav-link" href="<%= events_path(@user) %>">UPCOMING EVENTS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/<%= @user.id %>">YOUR EVENTS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_event_path(@user)%>">CREATE EVENTS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/signout">LOG OUT</a>
          </li>

          <% end %>
          <% if !user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="/signin">LOG IN </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/signup">SIGN UP</a>
          </li>
          <% end %>
        </ul>
      </div>

    </nav>
    <div id="flash"></div>
    <%- flash.keys.each do |kind| %>
    <div class=<%= kind %>>
      <h5><%= flash[kind] %></h5>
    </div>
    <%- end %>
    </div>



    <%= yield %>


    <nav class="navbar fixed-bottom navbar-light bg-light">
      <a class="navbar-brand" href="#">&copy; 2019<logo> RailsEventApp</logo></a>
    </nav>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>
  </body>

</html>